"""
Compliance Report Generator

Generates compliance reports from FIM data:
  - PCI-DSS Section 11.5 (File Integrity Monitoring)
  - SOX IT Controls (Change Management)

Uses reportlab for PDF generation.
"""
import io
import logging
from datetime import datetime, timedelta
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

logger = logging.getLogger("compliance_report")


class ComplianceReportService:

    @staticmethod
    def generate_pci_dss_report(data: dict) -> bytes:
        """Generate PCI-DSS 11.5 compliance report."""
        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=40, bottomMargin=40,
                               leftMargin=50, rightMargin=50)
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, spaceAfter=6)
        h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceBefore=12, spaceAfter=6)
        normal = styles["Normal"]
        small = ParagraphStyle("Small", parent=normal, fontSize=8, textColor=colors.HexColor("#64748b"))

        elements = []

        # Header
        elements.append(Paragraph("PCI-DSS Compliance Report", title_style))
        elements.append(Paragraph("Requirement 11.5 — File Integrity Monitoring", styles["Heading3"]))
        elements.append(Spacer(1, 10))

        # Report metadata
        meta = [
            ["Report Period:", f"{data.get('start_date', 'N/A')} to {data.get('end_date', 'N/A')}"],
            ["Generated:", datetime.now().strftime("%Y-%m-%d %H:%M IST")],
            ["Generated By:", data.get("generated_by", "FIM Enterprise")],
            ["Total Agents:", str(data.get("total_agents", 0))],
            ["Total Alerts:", str(data.get("total_alerts", 0))],
            ["Reports Generated:", str(data.get("total_reports", 0))],
        ]
        t = Table(meta, colWidths=[140, 350])
        t.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748b")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # Section 1: Requirement Summary
        elements.append(Paragraph("1. Requirement 11.5 Compliance Summary", h2))
        elements.append(Paragraph(
            "PCI-DSS Requirement 11.5 mandates deploying a change-detection mechanism "
            "(e.g., file-integrity monitoring tools) to alert personnel to unauthorized "
            "modification of critical system files, configuration files, or content files. "
            "The system must be configured to perform critical file comparisons at least weekly.",
            normal
        ))
        elements.append(Spacer(1, 10))

        compliance_items = [
            ["Control", "Status", "Evidence"],
            ["FIM agents deployed on critical systems",
             "COMPLIANT" if data.get("total_agents", 0) > 0 else "NON-COMPLIANT",
             f"{data.get('total_agents', 0)} agents active"],
            ["Automated file integrity scans",
             "COMPLIANT" if data.get("total_scans", 0) > 0 else "NON-COMPLIANT",
             f"{data.get('total_scans', 0)} scans in period (daily)"],
            ["Alert generation on file changes",
             "COMPLIANT" if data.get("total_alerts", 0) >= 0 else "NON-COMPLIANT",
             f"{data.get('total_alerts', 0)} alerts generated"],
            ["Daily review of changes",
             "COMPLIANT" if data.get("total_reports", 0) > 0 else "NON-COMPLIANT",
             f"{data.get('total_reports', 0)} daily reports"],
            ["Change tracking with audit trail",
             "COMPLIANT",
             "All changes logged with timestamps and user attribution"],
        ]
        ct = Table(compliance_items, colWidths=[180, 90, 220])
        ct.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#334155")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        # Color the status column
        for i in range(1, len(compliance_items)):
            status = compliance_items[i][1]
            color = colors.HexColor("#16a34a") if status == "COMPLIANT" else colors.HexColor("#dc2626")
            ct.setStyle(TableStyle([("TEXTCOLOR", (1, i), (1, i), color), ("FONTNAME", (1, i), (1, i), "Helvetica-Bold")]))
        elements.append(ct)
        elements.append(Spacer(1, 20))

        # Section 2: Agent Coverage
        elements.append(Paragraph("2. Monitored Systems", h2))
        if data.get("agents"):
            agent_table = [["Hostname", "IP Address", "Status", "Last Scan", "Open Alerts"]]
            for ag in data["agents"]:
                agent_table.append([
                    ag.get("hostname", ""), ag.get("ip_address", ""),
                    ag.get("status", ""), ag.get("last_scan", "N/A"),
                    str(ag.get("open_alerts", 0))
                ])
            at = Table(agent_table, colWidths=[150, 90, 70, 100, 70])
            at.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#334155")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ]))
            elements.append(at)

        elements.append(Spacer(1, 20))

        # Section 3: Alert Summary
        elements.append(Paragraph("3. Alert Summary by Severity", h2))
        if data.get("severity_breakdown"):
            sev_table = [["Severity", "Count", "Percentage"]]
            total = sum(data["severity_breakdown"].values()) or 1
            for sev in ["critical", "high", "medium", "low"]:
                count = data["severity_breakdown"].get(sev, 0)
                pct = f"{count/total*100:.1f}%"
                sev_table.append([sev.upper(), str(count), pct])
            st = Table(sev_table, colWidths=[120, 80, 80])
            st.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#334155")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ]))
            elements.append(st)

        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph(
            f"This report was automatically generated by FIM Enterprise on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M IST')}. "
            f"It provides evidence of compliance with PCI-DSS Requirement 11.5.",
            small
        ))

        doc.build(elements)
        buf.seek(0)
        return buf.read()
